### ISSUE TITLE
bin discretization issue

### ISSUE THREAD

**Issue by shifanmao** [SpakowitzLab/MCparallelMPI#3]
choosing DEL = 0.5 results in the following error
## Tried to allocate        64000  bins in MCvar_allocate

Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.

**Comment by qmacAstanford** [comment]
I increased the number of bins you can have before erroring out.  I left in the error out message to prevent us from doing something stupid.
