### ISSUE TITLE
PT off

### ISSUE THREAD

**Issue by shifanmao** [SpakowitzLab/MCparallelMPI#5]
I tried turning off parallel tempering by setting PT F (false) in input params and the following error shows up

At line 881 of file SIMcode/simMod.f90 (unit = 1, file = '???z_')
Fortran runtime error: File 'data/r0' already exists

I suspect it is due to copying r0 during initialization when PT = True?

**Comment by qmacAstanford** [comment]
I think I have fixed this.  Are you still having this problem?

**Comment by shifanmao** [comment]
Yep. PT now is an acceptable option. Thanks for the update!
