### ISSUE TITLE
Reptation Error

### ISSUE THREAD

**Issue by qmacAstanford** [SpakowitzLab/MCparallelMPI#6]
As shifan pointed out there is an error with reptation move for larger eps values.  The energy doesn't add up and the results don't fit theory of an non-interacting polymer.  I doubt this affects low eps runs.  Will investigate ....

**Comment by shifanmao** [comment]
with updated code, the error message regarding 'elastic energy discrepancy' is gone.

Single chain conformations also match well with analytical prediction (for input EPS=1.00).

Issue closed.
